### ISSUE TITLE
Not showing en/blog , corrected  HessamPostTranslation.php line 129

### ISSUE THREAD

**Issue by KALEFA** [sam-beri/laravel-blog-package#27]
Too few arguments to function HessamCMS\\Models\\HessamPostTranslation::url(), 0 passed ...  on get en/blog or search result, 

So changed HessamPostTranslation.php:129  from

`        return $auto_link ? "<a class='" . e($anchor_class) . "' href='" . e($this->url( )) . "'>$img</a>" : $img;`
to 
`        return $auto_link ? "<a class='" . e($anchor_class) . "' href='" . e($this->url( app()->getLocale() )) . "'>$img</a>" : $img;`

**Comment by sam-beri** [comment]
@KALEFA thanks for your consideration.

we will update it with new release. Thanks

**Comment by sam-beri** [comment]
would you please provide us with you email address?

thanks dear @KALEFA

**Comment by KALEFA** [comment]
Of course sam-beri ! . Is hansrey22@gmail.com  ;)
